# Server
server.port=5000

# JPA
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.hikari.initialization-fail-timeout=-1
spring.liquibase.change-log=classpath:db/master.yaml

# Amazon
amazon.accesskey=${AMAZON_ACCESSKEY}
amazon.bucket=${AMAZON_BUCKET}
amazon.region=${AMAZON_REGION}
amazon.secretkey=${AMAZON_SECRETKEY}

# JWT
jwt.secret=${JWT_SECRET}
jwt.cookie-name=${JWT_COOKIE_NAME}
jwt.maxage=${JWT_MAX_AGE}

# Email
spring.mail.host=${SPRING_MAIL_HOST}
spring.mail.port=${SPRING_MAIL_PORT}
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.enable=false
spring.mail.test-connection=true

# File handle
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Jackson
spring.jackson.deserialization.accept-empty-string-as-null-object=true
