# Server
server.port=5000

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.hikari.initialization-fail-timeout=-1

# Amazon
amazon.accesskey=${AMAZON_ACCESSKEY}
amazon.bucket=${AMAZON_BUCKET}
amazon.region=${AMAZON_REGION}
amazon.secretkey=${AMAZON_SECRETKEY}


# File handle
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Jackson
spring.jackson.deserialization.accept-empty-string-as-null-object=true
