driver=com.mysql.cj.jdbc.Driver

referenceUrl=hibernate:spring:br.com.photostyle.api\
  ?dialect=org.hibernate.dialect.MySQLDialect\
  &hibernate.physical_naming_strategy=org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy\
  &hibernate.implicit_naming_strategy=org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
